[project]
name = "niffler-e-2-e-tests"
version = "0.1.0"
description = ""
authors = [
    {name = "daniil",email = "dt.bedrin@interfax.ru"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker (>=38.2.0,<39.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "sqlmodel (>=0.0.32,<0.0.33)",
    "psycopg2-binary (>=2.9.11,<3.0.0)",
    "sqlalchemy (>=2.0.46,<3.0.0)",
    "allure-pytest (>=2.15.3,<3.0.0)",
    "curlify (>=3.0.0,<4.0.0)",
    "pkce (>=1.0.3,<2.0.0)",
    "radon (>=6.0.1,<7.0.0)",
    "grpcio-tools (>=1.78.0,<2.0.0)",
    "confluent-kafka (>=2.13.2,<3.0.0)",
    "jinja2 (>=3.1.6,<4.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
faker = "^38.2.0"
flake8 = "^7.3.0"

